plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.dtca.busvalidator.sdk'
    compileSdk 34

    defaultConfig {
        applicationId "com.dtca.busvalidator.sdk"
        minSdk 27
        targetSdk 34
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildFeatures {
        viewBinding true
    }
}

dependencies {

    implementation libs.appcompat
    implementation libs.material
    implementation libs.constraintlayout
    implementation libs.navigation.fragment
    implementation libs.navigation.ui
    implementation project(":app:busvalidatorsdk")
    implementation libs.gson
    compileOnly libs.lombok
    annotationProcessor libs.lombok
//    implementation fileTree(dir: 'C:\\Local Disk D_42320241129\\Project\\DS Project\\SDK\\app\\libs', include: ['*.aar', '*.jar'], exclude: [])
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core

}